default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%=Rails.application.credentials.database[:user]%>
  password: <%=Rails.application.credentials.database[:password]%>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: zammad_development

test:
  <<: *default
  database: zammad_test


production:
  <<: *default
  database: zammad_production